### ISSUE TITLE
Problem when running the source code

### ISSUE THREAD

**Issue by redatest** [ajaichemmanam/Emovere-ML#1]
Hello;

Thanks for providing this great piece of code, but when launching it displays only one frame of the videos stream.

Thanks in advance .

**Comment by ajaichemmanam** [comment]
Please provide more information such as which file you tried to run, python version, os, tensorflow version etc. So that I can help you. :)

**Comment by ajaichemmanam** [comment]
Closing Issue as there is no response. Please feel free to reopen it in case the issue still exists
